title:
  "Título do site"
  
description:
  "Descrição do site"

github:
  "username"

remote_theme:
  NossaSenhora/minima

header_pages:
  - content/inicio.md
  - content/oracao.md
  - content/novena.md

permalink:
  pretty

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
